
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 14:37:44 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 27;
  public static final int LBRACKET = 32;
  public static final int CHAR = 47;
  public static final int CONST = 28;
  public static final int QUESTIONMARK = 48;
  public static final int CASE = 38;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int LESS = 31;
  public static final int FOR = 19;
  public static final int MINUS = 25;
  public static final int RPAREN = 7;
  public static final int AND = 30;
  public static final int LESSEQUAL = 40;
  public static final int OR = 45;
  public static final int BOOL = 46;
  public static final int COMMA = 11;
  public static final int DIV = 23;
  public static final int PLUS = 10;
  public static final int IF = 16;
  public static final int DOT = 21;
  public static final int GRATHER = 35;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 26;
  public static final int RETURN = 9;
  public static final int RBRACKET = 41;
  public static final int EQUAL = 8;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int NUMBER = 14;
  public static final int MOD = 34;
  public static final int BREAK = 37;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int EQ = 43;
  public static final int SWITCH = 24;
  public static final int COLON = 18;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int READ = 39;
  public static final int ENUM = 33;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int PRINT = 12;
  public static final int LENGTH = 22;
  public static final int NOTEQ = 29;
  public static final int GRATHEREQUAL = 42;
}

